INSERT INTO DEPARTMENT (NAME, READ_ONLY, MANDATORY) VALUES ('Organisation', true, true);
INSERT INTO DEPARTMENT (NAME, READ_ONLY, MANDATORY) VALUES ('IT', false, false);
INSERT INTO DEPARTMENT (NAME, READ_ONLY, MANDATORY) VALUES ('Sales', false, false);
INSERT INTO DEPARTMENT (NAME, READ_ONLY, MANDATORY) VALUES ('HR', false, false);


INSERT INTO EMPLOYEE (NAME) VALUES ('Siddharth');
INSERT INTO EMPLOYEE (NAME) VALUES ('Akshay');
INSERT INTO EMPLOYEE (NAME) VALUES ('Aditya');
INSERT INTO EMPLOYEE (NAME) VALUES ('Anirudh');

INSERT INTO MAP_EMPLOYEE_DEPARTMENT(ID_EMPLOYEE, ID_DEPARTMENT) VALUES ((SELECT ID FROM EMPLOYEE WHERE NAME = 'Siddharth'),(SELECT ID FROM DEPARTMENT WHERE NAME='Organisation'));
INSERT INTO MAP_EMPLOYEE_DEPARTMENT(ID_EMPLOYEE, ID_DEPARTMENT) VALUES ((SELECT ID FROM EMPLOYEE WHERE NAME = 'Akshay'),(SELECT ID FROM DEPARTMENT WHERE NAME='Organisation'));
INSERT INTO MAP_EMPLOYEE_DEPARTMENT(ID_EMPLOYEE, ID_DEPARTMENT) VALUES ((SELECT ID FROM EMPLOYEE WHERE NAME = 'Aditya'),(SELECT ID FROM DEPARTMENT WHERE NAME='Organisation'));
INSERT INTO MAP_EMPLOYEE_DEPARTMENT(ID_EMPLOYEE, ID_DEPARTMENT) VALUES ((SELECT ID FROM EMPLOYEE WHERE NAME = 'Anirudh'),(SELECT ID FROM DEPARTMENT WHERE NAME='Organisation'));

