CREATE TABLE IF NOT EXISTS EMPLOYEE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(200));

CREATE TABLE IF NOT EXISTS DEPARTMENT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(200),
    READ_ONLY BOOLEAN,
    MANDATORY BOOLEAN
    );

CREATE TABLE IF NOT EXISTS MAP_EMPLOYEE_DEPARTMENT(
    ID_EMPLOYEE INT,
    ID_DEPARTMENT INT,
    FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE(ID),
    FOREIGN KEY (ID_DEPARTMENT) REFERENCES DEPARTMENT(ID),
    PRIMARY KEY (ID_EMPLOYEE, ID_DEPARTMENT)
    );