CREATE SEQUENCE IF NOT EXISTS DEPARTMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS EMPLOYEE_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS EMPLOYEE(
    ID INT PRIMARY KEY,
    NAME VARCHAR(255));

CREATE TABLE IF NOT EXISTS DEPARTMENT(
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    READ_ONLY BOOLEAN,
    MANDATORY BOOLEAN
    );

CREATE TABLE IF NOT EXISTS MAP_EMPLOYEE_DEPARTMENT(
    ID_EMPLOYEE INT,
    ID_DEPARTMENT INT,
    FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE(ID),
    FOREIGN KEY (ID_DEPARTMENT) REFERENCES DEPARTMENT(ID),
    PRIMARY KEY (ID_EMPLOYEE, ID_DEPARTMENT)
    );